# Vérification de l'API DigiMarket

Parcours de test de l'API REST : base de données, authentification, produits et commandes.

## 1. Préparer la base de données

Réinitialisation des tables, puis affichage de leur contenu avant les tests.

In [99]:
from pathlib import Path
import sqlite3
import pandas as pd
from IPython.display import display

database_path =  './digimarket.db'

# R2cupére le nom des tables de la base de données
with sqlite3.connect(database_path) as connection:
    table_names = [
        row[0]
        for row in connection.execute(
            "SELECT name FROM sqlite_master "
            "WHERE type = 'table' AND name NOT LIKE 'sqlite_%' "
            "ORDER BY name"
        )
    ]

print(f'Base utilisée : {database_path}')
print(f'Tables trouvées : {table_names}')

# Vide toutes les tables de la base de données
with sqlite3.connect(database_path) as connection:
    for table_name in table_names:
        connection.execute(f'DELETE FROM "{table_name}"')
        connection.commit()

# Affiche le contenu de toutes les tables de la base de données
for table_name in table_names:
    with sqlite3.connect(database_path) as connection:
        dataframe = pd.read_sql_query(
            f'SELECT * FROM "{table_name}"',
            connection,
        )
    print(f'\nTable : {table_name} ({len(dataframe)} ligne(s))')
    display(dataframe)

Base utilisée : ./digimarket.db
Tables trouvées : ['order', 'order_item', 'product', 'user']

Table : order (0 ligne(s))

Empty DataFrame
Columns: [id, utilisateur_id, date_commande, adresse_livraison, statut]
Index: []

Table : order_item (0 ligne(s))

Empty DataFrame
Columns: [id, commande_id, produit_id, quantite, prix_unitaire]
Index: []

Table : product (0 ligne(s))

Empty DataFrame
Columns: [id, nom, description, categorie, prix, quantite_stock, date_creation]
Index: []

Table : user (0 ligne(s))

Empty DataFrame
Columns: [id, email, password_hash, nom, role, date_creation]
Index: []

## 2. Créer le compte administrateur

Création d'un administrateur local pour tester les routes protégées.

In [100]:
import sqlite3
from datetime import datetime, timezone
import bcrypt  # pip install bcrypt

database_path = './digimarket.db'  # adapte le chemin si besoin

email = "admin@digimarket.com"
nom = "Administrateur"
role = "admin"
password = "admin"  

password_hash = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
date_creation = datetime.now(timezone.utc).isoformat()

with sqlite3.connect(database_path) as connection:
    existing = connection.execute(
        'SELECT id FROM "user" WHERE email = ?', (email,)
    ).fetchone()

    if existing:
        print(f"Un utilisateur avec l'email {email} existe déjà (id={existing[0]}).")
    else:
        connection.execute(
            'INSERT INTO "user" (email, password_hash, nom, role, date_creation) '
            'VALUES (?, ?, ?, ?, ?)',
            (email, password_hash, nom, role, date_creation),
        )
        connection.commit()
        print(f"Admin '{email}' créé avec succès.")

Admin 'admin@digimarket.com' créé avec succès.

In [101]:
with sqlite3.connect(database_path) as connection:
    dataframe = pd.read_sql_query(
        'SELECT * FROM "user"',
        connection,
    )
print(f'\nTable : {table_name} ({len(dataframe)} ligne(s))')
display(dataframe)

Table : user (1 ligne(s))

,id,email,password_hash,nom,role,date_creation
0,1,admin@digimarket.com,$2b$12$QKRnxHK3Z/lUgdnVpAS2gOJGGRZMx//PLes2ZzY...,Administrateur,admin,2026-09-22T17:14:37.008025+00:00

### Authentifier l'administrateur

Connexion via l'API et récupération du token JWT d'administration.

In [102]:
import requests

BASE_URL = "http://localhost:5000/api/auth"

response = requests.post(
    f"{BASE_URL}/login",
    json={
        "email": "admin@digimarket.com",
        "password": "admin",
    },
)

print("Status :", response.status_code)
print("URL    :", response.url)
print("Type   :", response.headers.get("Content-Type"))
print("Réponse:", response.text)

if response.status_code == 200:
    data = response.json()
    token = data["access_token"]
    print(f"\nToken JWT : {token}")

Status : 200
URL    : http://localhost:5000/api/auth/login
Type   : application/json
Réponse: {
  "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc5MDA5NzI3NywianRpIjoiYmViYjk2ZmUtMmFlNi00NzlhLTk1NjItYWExNWQ2MzIwY2Q0IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjEiLCJuYmYiOjE3OTAwOTcyNzcsImNzcmYiOiIxZDE5YjI0Ny01ODFjLTQ0ZjAtYjYzOC04ZDQyYTRjOWIzOWEiLCJleHAiOjE3OTAwOTgxNzcsInJvbGUiOiJhZG1pbiJ9.dZvyvNwSBSgzcueShOTg7hKsAXzSF-a3Zvkj3Sp5jY8",
  "user": {
    "email": "admin@digimarket.com",
    "id": 1,
    "username": "Administrateur"
  }
}


Token JWT : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc5MDA5NzI3NywianRpIjoiYmViYjk2ZmUtMmFlNi00NzlhLTk1NjItYWExNWQ2MzIwY2Q0IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjEiLCJuYmYiOjE3OTAwOTcyNzcsImNzcmYiOiIxZDE5YjI0Ny01ODFjLTQ0ZjAtYjYzOC04ZDQyYTRjOWIzOWEiLCJleHAiOjE3OTAwOTgxNzcsInJvbGUiOiJhZG1pbiJ9.dZvyvNwSBSgzcueShOTg7hKsAXzSF-a3Zvkj3Sp5jY8

## 3. Tester l'authentification

Création d'un client via l'API, puis vérification des connexions client et administrateur.

In [103]:
BASE_URL = "http://localhost:5000/api/auth"

client_data = {
    "username": "Client Test",
    "email": "client@digimarket.com",
    "password": "client",
}

response = requests.post(
    f"{BASE_URL}/register",
    json=client_data,
)

print("Status :", response.status_code)
print("URL    :", response.url)
print("Type   :", response.headers.get("Content-Type"))
print("Réponse:", response.text)

if response.status_code == 201:
    print("Client créé avec succès.")
elif response.status_code == 409:
    print("Ce client existe déjà.")

Status : 201
URL    : http://localhost:5000/api/auth/register
Type   : application/json
Réponse: {
  "message": "Utilisateur cr\u00e9\u00e9 avec succ\u00e8s"
}

Client créé avec succès.

In [104]:
with sqlite3.connect(database_path) as connection:
    dataframe = pd.read_sql_query(
        'SELECT * FROM "user"',
        connection,
    )
print(f'\nTable : {table_name} ({len(dataframe)} ligne(s))')
display(dataframe)

Table : user (2 ligne(s))

,id,email,password_hash,nom,role,date_creation
0,1,admin@digimarket.com,$2b$12$QKRnxHK3Z/lUgdnVpAS2gOJGGRZMx//PLes2ZzY...,Administrateur,admin,2026-09-22T17:14:37.008025+00:00
1,2,client@digimarket.com,$2b$12$Vn1v/hCNp8gx.y4Bk5Cqge4E1qbH/fWCWf9Eynu...,Client Test,client,2026-09-22 17:14:37.541721

### 3.1 Route `AUTH`

Les comptes sont créés et authentifiés avec les endpoints `/register` et `/login`.

#### Connexion du client

Le client utilise son token JWT pour accéder aux ressources autorisées.

In [105]:
response = requests.post(
    "http://localhost:5000/api/auth/login",
    json={
        "email": "client@digimarket.com",
        "password": "client",
    },
)

client_token = response.json().get("access_token")
print("Status :", response.status_code)
print(response.json()["user"]["username"], 
      f"(id : {response.json()["user"]["id"]}) ",
        "est connecté avec succès.\n",
      f"Le token d'accès est : {client_token}")

Status : 200
Client Test (id : 2)  est connecté avec succès.
 Le token d'accès est : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc5MDA5NzI3NywianRpIjoiNDEzMjA0MmUtOTFlMy00YmY4LTg5NDUtZmU4YzNhNjk0MzI2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjIiLCJuYmYiOjE3OTAwOTcyNzcsImNzcmYiOiIyODcwNjNlYy03MTNmLTQwN2YtYWJkOC1kMjZhYjliZGU1OTAiLCJleHAiOjE3OTAwOTgxNzcsInJvbGUiOiJjbGllbnQifQ.wen-Dcc0QZ_NnN0SfG8QKcpofVFFoVp1onyzmUDnM7Y

#### Connexion de l'administrateur

L'administrateur obtient un token JWT avec les droits nécessaires aux opérations de gestion.

In [106]:
response = requests.post(
    "http://localhost:5000/api/auth/login",
    json={
        "email": "admin@digimarket.com",
        "password": "admin",
    },
)

admin_token = response.json().get("access_token")
print("Status :", response.status_code)
print(response.json()["user"]["username"], 
      f"(id : {response.json()["user"]["id"]}) ",
        "est connecté avec succès.\n",
      f"Le token d'accès est : {admin_token}")

Status : 200
Administrateur (id : 1)  est connecté avec succès.
 Le token d'accès est : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc5MDA5NzI3OCwianRpIjoiOGJmYjlhMmYtZTU5ZC00MzhkLThlOWItOTFmMjIyNzlhYWM2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjEiLCJuYmYiOjE3OTAwOTcyNzgsImNzcmYiOiI0ODY2YTE3ZC00OGEwLTRmYTAtODJmNi1lZjRmYjliMjU4MTMiLCJleHAiOjE3OTAwOTgxNzgsInJvbGUiOiJhZG1pbiJ9.YwNvzw8hSAiloB176TFIEn18mJ9TJtyTMGXtlvxgaLI

## 4. Gérer les produits

Vérification des droits d'accès, création des produits et consultation du catalogue.

### Ajouter des produits

Tentative avec un client, puis création complète du catalogue avec l'administrateur.

In [107]:
produits = [
    # Catégorie : Ordinateurs
    {"nom": "PC Portable Gamer 15.6\" RTX 4060", "description": "Ordinateur portable gaming, écran 144Hz, 16 Go RAM, SSD 512 Go", "categorie": "Ordinateurs", "prix": 999.00, "quantite_stock": 8},
    {"nom": "PC Fixe Gaming Tower RGB", "description": "Tour gaming avec ventilation RGB, Core i7, RTX 4070, 32 Go RAM", "categorie": "Ordinateurs", "prix": 1450.00, "quantite_stock": 5},
    {"nom": "PC All-in-One 24\" Tactile", "description": "Ordinateur tout-en-un avec écran tactile 24 pouces, idéal bureautique", "categorie": "Ordinateurs", "prix": 649.00, "quantite_stock": 12},
    {"nom": "Mini PC Compact Bureau", "description": "Mini PC silencieux pour usage bureautique, format compact", "categorie": "Ordinateurs", "prix": 320.00, "quantite_stock": 15},

    # Catégorie : Accessoires
    {"nom": "Clavier Mécanique RGB", "description": "Clavier mécanique gamer, rétroéclairage RGB personnalisable", "categorie": "Accessoires", "prix": 79.90, "quantite_stock": 30},
    {"nom": "Souris Gaming Sans Fil", "description": "Souris ergonomique haute précision, capteur optique 16000 DPI", "categorie": "Accessoires", "prix": 49.90, "quantite_stock": 25},
    {"nom": "Casque Gamer Surround 7.1", "description": "Casque gaming avec son surround et micro antibruit", "categorie": "Accessoires", "prix": 89.00, "quantite_stock": 18},
    {"nom": "Écran Gaming 27\" 165Hz", "description": "Moniteur gaming incurvé, résolution QHD, temps de réponse 1ms", "categorie": "Accessoires", "prix": 279.00, "quantite_stock": 10},
]


def create_product(token, produit):
    headers = {"Authorization": f"Bearer {token}"} if token else {}
    response = requests.post(
        "http://localhost:5000/api/produits",
        json=produit,
        headers=headers,
    )
    print("Status:", response.status_code)
    print("Body brut:", response.text)
    try:
        return response.status_code, response.json()
    except ValueError:
        return response.status_code, None

#### Contrôle d'accès : client

Un client ne doit pas pouvoir créer de produit.

In [108]:
status, body = create_product(client_token, produits[0])
print(status, body)

Status: 403
Body brut: {
  "error": "Acc\u00e8s r\u00e9serv\u00e9 aux administrateurs"
}

403 {'error': 'Accès réservé aux administrateurs'}

#### Contrôle d'accès : administrateur

L'administrateur peut créer les produits du catalogue.

In [109]:
for produit in produits:
    status, body = create_product(admin_token, produit)
    print(status, body)

Status: 201
Body brut: {
  "categorie": "Ordinateurs",
  "date_creation": "2026-09-22T17:14:38.111794",
  "description": "Ordinateur portable gaming, \u00e9cran 144Hz, 16 Go RAM, SSD 512 Go",
  "id": 1,
  "nom": "PC Portable Gamer 15.6\" RTX 4060",
  "prix": 999.0,
  "quantite_stock": 8
}

201 {'categorie': 'Ordinateurs', 'date_creation': '2026-09-22T17:14:38.111794', 'description': 'Ordinateur portable gaming, écran 144Hz, 16 Go RAM, SSD 512 Go', 'id': 1, 'nom': 'PC Portable Gamer 15.6" RTX 4060', 'prix': 999.0, 'quantite_stock': 8}
Status: 201
Body brut: {
  "categorie": "Ordinateurs",
  "date_creation": "2026-09-22T17:14:38.125931",
  "description": "Tour gaming avec ventilation RGB, Core i7, RTX 4070, 32 Go RAM",
  "id": 2,
  "nom": "PC Fixe Gaming Tower RGB",
  "prix": 1450.0,
  "quantite_stock": 5
}

201 {'categorie': 'Ordinateurs', 'date_creation': '2026-09-22T17:14:38.125931', 'description': 'Tour gaming avec ventilation RGB, Core i7, RTX 4070, 32 Go RAM', 'id': 2, 'nom': 'PC Fixe Gaming Tower RGB', 'prix': 1450.0, 'quantite_stock': 5}
Status: 201
Body brut: {
  "categorie": "Ordinateurs",
  "date_creation": "2026-09-22T17:14:38.146145",
  "description": "Ordinateur tout-en-un avec \u00e9cran tactile 24 pouces, id\u00e9al bureautique",
  "id": 3,
  "nom": "PC All-in-One 24\" Tactile",
  "prix": 649.0,
  "quantite_stock": 12
}

201 {'categorie': 'Ordinateurs', 'date_creation': '2026-09-22T17:14:38.146145', 'description': 'Ordinateur tout-en-un avec écran tactile 24 pouces, idéal bureautique', 'id': 3, 'nom': 'PC All-in-One 24" Tactile', 'prix': 649.0, 'quantite_stock': 12}
Status: 201
Body brut: {
  "categorie": "Ordinateurs",
  "date_creation": "2026-09-22T17:14:38.157446",
  "description": "Mini PC silencieux pour usage bureautique, format compact",
  "id": 4,
  "nom": "Mini PC Compact Bureau",
  "prix": 320.0,
  "quantite_stock": 15
}

201 {'categorie': 'Ordinateurs', 'date_creation': '2026-09-22T17:14:38.157446', 'description': 'Mini PC silencieux pour usage bureautique, format compact', 'id': 4, 'nom': 'Mini PC Compact Bureau', 'prix': 320.0, 'quantite_stock': 15}
Status: 201
Body brut: {
  "categorie": "Accessoires",
  "date_creation": "2026-09-22T17:14:38.168992",
  "description": "Clavier m\u00e9canique gamer, r\u00e9tro\u00e9clairage RGB personnalisable",
  "id": 5,
  "nom": "Clavier M\u00e9canique RGB",
  "prix": 79.9,
  "quantite_stock": 30
}

201 {'categorie': 'Accessoires', 'date_creation': '2026-09-22T17:14:38.168992', 'description': 'Clavier mécanique gamer, rétroéclairage RGB personnalisable', 'id': 5, 'nom': 'Clavier Mécanique RGB', 'prix': 79.9, 'quantite_stock': 30}
Status: 201
Body brut: {
  "categorie": "Accessoires",
  "date_creation": "2026-09-22T17:14:38.179132",
  "description": "Souris ergonomique haute pr\u00e9cision, capteur optique 16000 DPI",
  "id": 6,
  "nom": "Souris Gaming Sans Fil",
  "prix": 49.9,
  "quantite_stock": 25
}

201 {'categorie': 'Accessoires', 'date_creation': '2026-09-22T17:14:38.179132', 'description': 'Souris ergonomique haute précision, capteur optique 16000 DPI', 'id': 6, 'nom': 'Souris Gaming Sans Fil', 'prix': 49.9, 'quantite_stock': 25}
Status: 201
Body brut: {
  "categorie": "Accessoires",
  "date_creation": "2026-09-22T17:14:38.190013",
  "description": "Casque gaming avec son surround et micro antibruit",
  "id": 7,
  "nom": "Casque Gamer Surround 7.1",
  "prix": 89.0,
  "quantite_stock": 18
}

201 {'categorie': 'Accessoires', 'date_creation': '2026-09-22T17:14:38.190013', 'description': 'Casque gaming avec son surround et micro antibruit', 'id': 7, 'nom': 'Casque Gamer Surround 7.1', 'prix': 89.0, 'quantite_stock': 18}
Status: 201
Body brut: {
  "categorie": "Accessoires",
  "date_creation": "2026-09-22T17:14:38.205133",
  "description": "Moniteur gaming incurv\u00e9, r\u00e9solution QHD, temps de r\u00e9ponse 1ms",
  "id": 8,
  "nom": "\u00c9cran Gaming 27\" 165Hz",
  "prix": 279.0,
  "quantite_stock": 10
}

201 {'categorie': 'Accessoires', 'date_creation': '2026-09-22T17:14:38.205133', 'description': 'Moniteur gaming incurvé, résolution QHD, temps de réponse 1ms', 'id': 8, 'nom': 'Écran Gaming 27" 165Hz', 'prix': 279.0, 'quantite_stock': 10}

### Obtenir toute la liste des produits

In [110]:
def get_products(token):
    headers = {"Authorization": f"Bearer {token}"} if token else {}
    response = requests.get(
        "http://localhost:5000/api/produits",
        headers=headers,
    )
    return response.status_code, response.json()

In [111]:
status, body = get_products(admin_token)

df = pd.DataFrame(body)
df

,categorie,date_creation,description,id,nom,prix,quantite_stock
0,Ordinateurs,2026-09-22T17:14:38.111794,"Ordinateur portable gaming, écran 144Hz, 16 Go...",1,"PC Portable Gamer 15.6"" RTX 4060",999.0,8
1,Ordinateurs,2026-09-22T17:14:38.125931,"Tour gaming avec ventilation RGB, Core i7, RTX...",2,PC Fixe Gaming Tower RGB,1450.0,5
2,Ordinateurs,2026-09-22T17:14:38.146145,Ordinateur tout-en-un avec écran tactile 24 po...,3,"PC All-in-One 24"" Tactile",649.0,12
3,Ordinateurs,2026-09-22T17:14:38.157446,"Mini PC silencieux pour usage bureautique, for...",4,Mini PC Compact Bureau,320.0,15
4,Accessoires,2026-09-22T17:14:38.168992,"Clavier mécanique gamer, rétroéclairage RGB pe...",5,Clavier Mécanique RGB,79.9,30
5,Accessoires,2026-09-22T17:14:38.179132,"Souris ergonomique haute précision, capteur op...",6,Souris Gaming Sans Fil,49.9,25
6,Accessoires,2026-09-22T17:14:38.190013,Casque gaming avec son surround et micro antib...,7,Casque Gamer Surround 7.1,89.0,18
7,Accessoires,2026-09-22T17:14:38.205133,"Moniteur gaming incurvé, résolution QHD, temps...",8,"Écran Gaming 27"" 165Hz",279.0,10

### Obtenir un produit avec son id

In [112]:
def get_product_by_id(token, id_product):
    headers = {"Authorization": f"Bearer {token}"} if token else {}
    response = requests.get(
        f"http://localhost:5000/api/produits/{id_product}",
        headers=headers,
    )
    return response.status_code, response.json()

status, body = get_product_by_id(client_token, 7)

product_by_id = pd.DataFrame([body])
product_by_id

,categorie,date_creation,description,id,nom,prix,quantite_stock
0,Accessoires,2026-09-22T17:14:38.190013,Casque gaming avec son surround et micro antib...,7,Casque Gamer Surround 7.1,89.0,18

### Modifier un produit

Mise à jour d'un produit existant avec le token administrateur.

In [113]:
def modify_product(token,product):
    headers = {"Authorization": f"Bearer {token}"} if token else {}
    response = requests.put(
        f"http://localhost:5000/api/produits/{product['id']}",
        json=product,
        headers=headers,
    )
    return response.status_code, response.json()

In [114]:
product={ "id": 7,
          "nom": "modification ok",
          "categorie": "Autres",
          "description" : "à voir",
          "quantite_stock" : 100
}

status, body = modify_product(admin_token, product)

new_line = pd.DataFrame([body])
new_line

,categorie,date_creation,description,id,nom,prix,quantite_stock
0,Autres,2026-09-22T17:14:38.190013,à voir,7,Casque Gamer Surround 7.1,89.0,100

## 5. Gérer les commandes

Dernière étape du parcours : tester la consultation et la gestion des commandes.