# Vérification de l'API DigiMarket

Parcours de test de l'API REST : base de données, authentification, produits et commandes.

## 1. Préparation de la base de données

Réinitialisation des tables, puis affichage de leur contenu avant les tests.

In [64]:
from pathlib import Path
import sqlite3
import pandas as pd
from IPython.display import display

database_path =  './digimarket.db'

# R2cupére le nom des tables de la base de données
with sqlite3.connect(database_path) as connection:
    table_names = [
        row[0]
        for row in connection.execute(
            "SELECT name FROM sqlite_master "
            "WHERE type = 'table' AND name NOT LIKE 'sqlite_%' "
            "ORDER BY name"
        )
    ]

print(f'Base utilisée : {database_path}')
print(f'Tables trouvées : {table_names}')

# Vide toutes les tables de la base de données
with sqlite3.connect(database_path) as connection:
    for table_name in table_names:
        connection.execute(f'DELETE FROM "{table_name}"')
        connection.commit()

# Affiche le contenu de toutes les tables de la base de données
for table_name in table_names:
    with sqlite3.connect(database_path) as connection:
        dataframe = pd.read_sql_query(
            f'SELECT * FROM "{table_name}"',
            connection,
        )
    print(f'\nTable : {table_name} ({len(dataframe)} ligne(s))')
    display(dataframe)

Base utilisée : ./digimarket.db
Tables trouvées : ['order', 'order_item', 'product', 'user']

Table : order (0 ligne(s))

Empty DataFrame
Columns: [id, utilisateur_id, date_commande, adresse_livraison, statut]
Index: []

Table : order_item (0 ligne(s))

Empty DataFrame
Columns: [id, commande_id, produit_id, quantite, prix_unitaire]
Index: []

Table : product (0 ligne(s))

Empty DataFrame
Columns: [id, nom, description, categorie, prix, quantite_stock, date_creation]
Index: []

Table : user (0 ligne(s))

Empty DataFrame
Columns: [id, email, password_hash, nom, role, date_creation]
Index: []

## 2. Création d'un compte administrateur

Création d'un administrateur local pour tester les routes protégées.

In [65]:
import sqlite3
from datetime import datetime, timezone
import bcrypt  # pip install bcrypt

database_path = './digimarket.db'  # adapte le chemin si besoin

email = "admin@digimarket.com"
nom = "Administrateur"
role = "admin"
password = "admin"  

password_hash = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
date_creation = datetime.now(timezone.utc).isoformat()

with sqlite3.connect(database_path) as connection:
    existing = connection.execute(
        'SELECT id FROM "user" WHERE email = ?', (email,)
    ).fetchone()

    if existing:
        print(f"Un utilisateur avec l'email {email} existe déjà (id={existing[0]}).")
    else:
        connection.execute(
            'INSERT INTO "user" (email, password_hash, nom, role, date_creation) '
            'VALUES (?, ?, ?, ?, ?)',
            (email, password_hash, nom, role, date_creation),
        )
        connection.commit()
        print(f"Admin '{email}' créé avec succès.")

Admin 'admin@digimarket.com' créé avec succès.

In [66]:
with sqlite3.connect(database_path) as connection:
    dataframe = pd.read_sql_query(
        'SELECT * FROM "user"',
        connection,
    )
print(f'\nTable : {table_name} ({len(dataframe)} ligne(s))')
display(dataframe)

Table : user (1 ligne(s))

,id,email,password_hash,nom,role,date_creation
0,1,admin@digimarket.com,$2b$12$CTQ9JELsjvafL8g11SwzaOInnB9Sly731VqD0uc...,Administrateur,admin,2026-09-25T16:47:56.127824+00:00

### Authentifier l'administrateur

Connexion via l'API et récupération du token JWT d'administration.

In [67]:
import requests

BASE_URL = "http://localhost:5000/api/auth"

response = requests.post(
    f"{BASE_URL}/login",
    json={
        "email": "admin@digimarket.com",
        "password": "admin",
    },
)

print("Status :", response.status_code)
print("URL    :", response.url)
print("Type   :", response.headers.get("Content-Type"))
print("Réponse:", response.text)

if response.status_code == 200:
    data = response.json()
    token = data["access_token"]

Status : 200
URL    : http://localhost:5000/api/auth/login
Type   : application/json
Réponse: {
  "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc5MDM1NDg3NiwianRpIjoiYTZkYzhjYjktNDlmZS00ZWM0LWEwYjYtYTRjYjE1YjQzMTkyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjEiLCJuYmYiOjE3OTAzNTQ4NzYsImNzcmYiOiIwYTRlYzc4OS04NWNlLTRjN2YtYTg3Yy02ODBiNzU2MTIyYTciLCJleHAiOjE3OTAzNTU3NzYsInJvbGUiOiJhZG1pbiJ9.2VE9_TvJx6TqOAXRpRqW48liF5vLe97POMO2E-N0FTA",
  "user": {
    "email": "admin@digimarket.com",
    "id": 1,
    "username": "Administrateur"
  }
}

## 3. Teste de la route AUTH

### 3.1 Création d'un client 

Création d'un client via l'API.
Les comptes sont créés avec le endpoint `/register`.

In [68]:
BASE_URL = "http://localhost:5000/api/auth"

client_data = {
    "username": "Client Test",
    "email": "client@digimarket.com",
    "password": "client",
}

response = requests.post(
    f"{BASE_URL}/register",
    json=client_data,
)

print("Status :", response.status_code)
print("URL    :", response.url)
print("Type   :", response.headers.get("Content-Type"))
print("Réponse:", response.text)

if response.status_code == 201:
    print("Client créé avec succès.")
elif response.status_code == 409:
    print("Ce client existe déjà.")

Status : 201
URL    : http://localhost:5000/api/auth/register
Type   : application/json
Réponse: {
  "message": "Utilisateur cr\u00e9\u00e9 avec succ\u00e8s"
}

Client créé avec succès.

In [69]:
with sqlite3.connect(database_path) as connection:
    dataframe = pd.read_sql_query(
        'SELECT * FROM "user"',
        connection,
    )
print(f'\nTable : {table_name} ({len(dataframe)} ligne(s))')
display(dataframe)

Table : user (2 ligne(s))

,id,email,password_hash,nom,role,date_creation
0,1,admin@digimarket.com,$2b$12$CTQ9JELsjvafL8g11SwzaOInnB9Sly731VqD0uc...,Administrateur,admin,2026-09-25T16:47:56.127824+00:00
1,2,client@digimarket.com,$2b$12$QKBGB3znZp0B/J7.vjfr2uAAvulMZYRNAV6IKNT...,Client Test,client,2026-09-25 16:47:56.674071

### 3.2 Login des utilisateurs

Les comptes sont authentifiés avec le endpoint `/login`.

#### Connexion du client

Le client utilise son token JWT pour accéder aux ressources autorisées.

In [70]:
response = requests.post(
    "http://localhost:5000/api/auth/login",
    json={
        "email": "client@digimarket.com",
        "password": "client",
    },
)

client_token = response.json().get("access_token")
print("Status :", response.status_code)
print(response.json()["user"]["username"], 
      f"(id : {response.json()["user"]["id"]}) ",
        "est connecté avec succès.\n",
      f"Le token d'accès est : {client_token}")

Status : 200
Client Test (id : 2)  est connecté avec succès.
 Le token d'accès est : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc5MDM1NDg3NiwianRpIjoiNjQzY2I1ZjYtYmJjOS00N2RhLWFlNTctNzdlOTExZjM4ZDE0IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjIiLCJuYmYiOjE3OTAzNTQ4NzYsImNzcmYiOiIwOWYwZjZhMC04OTMyLTQ0NWQtYTA2Yy03YjIwNWM0MDRjZjciLCJleHAiOjE3OTAzNTU3NzYsInJvbGUiOiJjbGllbnQifQ.aPI63TN4McrJd5Kz2RPMn7gNB8zYB6V_6oQxMaQNt6w

#### Connexion de l'administrateur

L'administrateur obtient un token JWT avec les droits nécessaires aux opérations de gestion.

In [71]:
response = requests.post(
    "http://localhost:5000/api/auth/login",
    json={
        "email": "admin@digimarket.com",
        "password": "admin",
    },
)

admin_token = response.json().get("access_token")
print("Status :", response.status_code)
print(response.json()["user"]["username"], 
      f"(id : {response.json()["user"]["id"]}) ",
        "est connecté avec succès.\n",
      f"Le token d'accès est : {admin_token}")

Status : 200
Administrateur (id : 1)  est connecté avec succès.
 Le token d'accès est : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc5MDM1NDg3NywianRpIjoiNzM4NzY3ZjgtZTZiNC00YTJmLThkOTMtM2ZkNWY1MWQxOWEzIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjEiLCJuYmYiOjE3OTAzNTQ4NzcsImNzcmYiOiJlOTg5ZDQzNS0yY2I1LTRmOGItYmYzZS1iMWZkYzUwNjIwMTUiLCJleHAiOjE3OTAzNTU3NzcsInJvbGUiOiJhZG1pbiJ9.N1Bw2kTwTgBeGZ9jUm_T7b011lPm6yuWMWYQn4QTpxE

## 4. Gesyion des produits

Vérification des droits d'accès, création des produits et consultation du catalogue.

### Ajouter des produits

Tentative avec un client, puis création complète du catalogue avec l'administrateur.

In [72]:
produits = [
    # Catégorie : Ordinateurs
    {"nom": "PC Portable Gamer 15.6\" RTX 4060", "description": "Ordinateur portable gaming, écran 144Hz, 16 Go RAM, SSD 512 Go", "categorie": "Ordinateurs", "prix": 999.00, "quantite_stock": 8},
    {"nom": "PC Fixe Gaming Tower RGB", "description": "Tour gaming avec ventilation RGB, Core i7, RTX 4070, 32 Go RAM", "categorie": "Ordinateurs", "prix": 1450.00, "quantite_stock": 5},
    {"nom": "PC All-in-One 24\" Tactile", "description": "Ordinateur tout-en-un avec écran tactile 24 pouces, idéal bureautique", "categorie": "Ordinateurs", "prix": 649.00, "quantite_stock": 12},
    {"nom": "Mini PC Compact Bureau", "description": "Mini PC silencieux pour usage bureautique, format compact", "categorie": "Ordinateurs", "prix": 320.00, "quantite_stock": 15},

    # Catégorie : Accessoires
    {"nom": "Clavier Mécanique RGB", "description": "Clavier mécanique gamer, rétroéclairage RGB personnalisable", "categorie": "Accessoires", "prix": 79.90, "quantite_stock": 30},
    {"nom": "Souris Gaming Sans Fil", "description": "Souris ergonomique haute précision, capteur optique 16000 DPI", "categorie": "Accessoires", "prix": 49.90, "quantite_stock": 25},
    {"nom": "Casque Gamer Surround 7.1", "description": "Casque gaming avec son surround et micro antibruit", "categorie": "Accessoires", "prix": 89.00, "quantite_stock": 18},
    {"nom": "Écran Gaming 27\" 165Hz", "description": "Moniteur gaming incurvé, résolution QHD, temps de réponse 1ms", "categorie": "Accessoires", "prix": 279.00, "quantite_stock": 10},
]


def create_product(token, produit):
    headers = {"Authorization": f"Bearer {token}"} if token else {}
    response = requests.post(
        "http://localhost:5000/api/produits",
        json=produit,
        headers=headers,
    )
    print("Status:", response.status_code)
    print("Body brut:", response.text)
    try:
        return response.status_code, response.json()
    except ValueError:
        return response.status_code, None

#### Contrôle d'accès : client

Un client ne doit pas pouvoir créer de produit.

In [73]:
status, body = create_product(client_token, produits[0])
print(status, body)

Status: 403
Body brut: {
  "error": "Acc\u00e8s r\u00e9serv\u00e9 aux administrateurs"
}

403 {'error': 'Accès réservé aux administrateurs'}

#### Contrôle d'accès : administrateur

L'administrateur peut créer les produits du catalogue.

In [74]:
for produit in produits:
    status, body = create_product(admin_token, produit)
    print(status, body)

Status: 201
Body brut: {
  "categorie": "Ordinateurs",
  "date_creation": "2026-09-25T16:47:57.264446",
  "description": "Ordinateur portable gaming, \u00e9cran 144Hz, 16 Go RAM, SSD 512 Go",
  "id": 1,
  "nom": "PC Portable Gamer 15.6\" RTX 4060",
  "prix": 999.0,
  "quantite_stock": 8
}

201 {'categorie': 'Ordinateurs', 'date_creation': '2026-09-25T16:47:57.264446', 'description': 'Ordinateur portable gaming, écran 144Hz, 16 Go RAM, SSD 512 Go', 'id': 1, 'nom': 'PC Portable Gamer 15.6" RTX 4060', 'prix': 999.0, 'quantite_stock': 8}
Status: 201
Body brut: {
  "categorie": "Ordinateurs",
  "date_creation": "2026-09-25T16:47:57.283631",
  "description": "Tour gaming avec ventilation RGB, Core i7, RTX 4070, 32 Go RAM",
  "id": 2,
  "nom": "PC Fixe Gaming Tower RGB",
  "prix": 1450.0,
  "quantite_stock": 5
}

201 {'categorie': 'Ordinateurs', 'date_creation': '2026-09-25T16:47:57.283631', 'description': 'Tour gaming avec ventilation RGB, Core i7, RTX 4070, 32 Go RAM', 'id': 2, 'nom': 'PC Fixe Gaming Tower RGB', 'prix': 1450.0, 'quantite_stock': 5}
Status: 201
Body brut: {
  "categorie": "Ordinateurs",
  "date_creation": "2026-09-25T16:47:57.297897",
  "description": "Ordinateur tout-en-un avec \u00e9cran tactile 24 pouces, id\u00e9al bureautique",
  "id": 3,
  "nom": "PC All-in-One 24\" Tactile",
  "prix": 649.0,
  "quantite_stock": 12
}

201 {'categorie': 'Ordinateurs', 'date_creation': '2026-09-25T16:47:57.297897', 'description': 'Ordinateur tout-en-un avec écran tactile 24 pouces, idéal bureautique', 'id': 3, 'nom': 'PC All-in-One 24" Tactile', 'prix': 649.0, 'quantite_stock': 12}
Status: 201
Body brut: {
  "categorie": "Ordinateurs",
  "date_creation": "2026-09-25T16:47:57.311880",
  "description": "Mini PC silencieux pour usage bureautique, format compact",
  "id": 4,
  "nom": "Mini PC Compact Bureau",
  "prix": 320.0,
  "quantite_stock": 15
}

201 {'categorie': 'Ordinateurs', 'date_creation': '2026-09-25T16:47:57.311880', 'description': 'Mini PC silencieux pour usage bureautique, format compact', 'id': 4, 'nom': 'Mini PC Compact Bureau', 'prix': 320.0, 'quantite_stock': 15}
Status: 201
Body brut: {
  "categorie": "Accessoires",
  "date_creation": "2026-09-25T16:47:57.325659",
  "description": "Clavier m\u00e9canique gamer, r\u00e9tro\u00e9clairage RGB personnalisable",
  "id": 5,
  "nom": "Clavier M\u00e9canique RGB",
  "prix": 79.9,
  "quantite_stock": 30
}

201 {'categorie': 'Accessoires', 'date_creation': '2026-09-25T16:47:57.325659', 'description': 'Clavier mécanique gamer, rétroéclairage RGB personnalisable', 'id': 5, 'nom': 'Clavier Mécanique RGB', 'prix': 79.9, 'quantite_stock': 30}
Status: 201
Body brut: {
  "categorie": "Accessoires",
  "date_creation": "2026-09-25T16:47:57.337611",
  "description": "Souris ergonomique haute pr\u00e9cision, capteur optique 16000 DPI",
  "id": 6,
  "nom": "Souris Gaming Sans Fil",
  "prix": 49.9,
  "quantite_stock": 25
}

201 {'categorie': 'Accessoires', 'date_creation': '2026-09-25T16:47:57.337611', 'description': 'Souris ergonomique haute précision, capteur optique 16000 DPI', 'id': 6, 'nom': 'Souris Gaming Sans Fil', 'prix': 49.9, 'quantite_stock': 25}
Status: 201
Body brut: {
  "categorie": "Accessoires",
  "date_creation": "2026-09-25T16:47:57.349812",
  "description": "Casque gaming avec son surround et micro antibruit",
  "id": 7,
  "nom": "Casque Gamer Surround 7.1",
  "prix": 89.0,
  "quantite_stock": 18
}

201 {'categorie': 'Accessoires', 'date_creation': '2026-09-25T16:47:57.349812', 'description': 'Casque gaming avec son surround et micro antibruit', 'id': 7, 'nom': 'Casque Gamer Surround 7.1', 'prix': 89.0, 'quantite_stock': 18}
Status: 201
Body brut: {
  "categorie": "Accessoires",
  "date_creation": "2026-09-25T16:47:57.366296",
  "description": "Moniteur gaming incurv\u00e9, r\u00e9solution QHD, temps de r\u00e9ponse 1ms",
  "id": 8,
  "nom": "\u00c9cran Gaming 27\" 165Hz",
  "prix": 279.0,
  "quantite_stock": 10
}

201 {'categorie': 'Accessoires', 'date_creation': '2026-09-25T16:47:57.366296', 'description': 'Moniteur gaming incurvé, résolution QHD, temps de réponse 1ms', 'id': 8, 'nom': 'Écran Gaming 27" 165Hz', 'prix': 279.0, 'quantite_stock': 10}

### Obtenir toute la liste des produits

In [75]:
def get_products(token):
    headers = {"Authorization": f"Bearer {token}"} if token else {}
    response = requests.get(
        "http://localhost:5000/api/produits",
        headers=headers,
    )
    return response.status_code, response.json()

In [76]:
status, body = get_products(admin_token)

df = pd.DataFrame(body)
df

,categorie,date_creation,description,id,nom,prix,quantite_stock
0,Ordinateurs,2026-09-25T16:47:57.264446,"Ordinateur portable gaming, écran 144Hz, 16 Go...",1,"PC Portable Gamer 15.6"" RTX 4060",999.0,8
1,Ordinateurs,2026-09-25T16:47:57.283631,"Tour gaming avec ventilation RGB, Core i7, RTX...",2,PC Fixe Gaming Tower RGB,1450.0,5
2,Ordinateurs,2026-09-25T16:47:57.297897,Ordinateur tout-en-un avec écran tactile 24 po...,3,"PC All-in-One 24"" Tactile",649.0,12
3,Ordinateurs,2026-09-25T16:47:57.311880,"Mini PC silencieux pour usage bureautique, for...",4,Mini PC Compact Bureau,320.0,15
4,Accessoires,2026-09-25T16:47:57.325659,"Clavier mécanique gamer, rétroéclairage RGB pe...",5,Clavier Mécanique RGB,79.9,30
5,Accessoires,2026-09-25T16:47:57.337611,"Souris ergonomique haute précision, capteur op...",6,Souris Gaming Sans Fil,49.9,25
6,Accessoires,2026-09-25T16:47:57.349812,Casque gaming avec son surround et micro antib...,7,Casque Gamer Surround 7.1,89.0,18
7,Accessoires,2026-09-25T16:47:57.366296,"Moniteur gaming incurvé, résolution QHD, temps...",8,"Écran Gaming 27"" 165Hz",279.0,10

### Obtenir un produit avec son nom ou sa description

In [77]:
def get_product_by_name_or_description(token, nom, description):
    headers = {"Authorization": f"Bearer {token}"} if token else {}
    response = requests.get(
        f"http://localhost:5000/api/produits/",
        headers=headers,
        params={"nom": nom, "description": description}
    )
    return response.status_code, response.json()

status, body = get_product_by_name_or_description(client_token, "Pc", "Tour")
if status != 200:
    print(f"Erreur {status}: {body}")
else:
    product_by_name_or_description = pd.DataFrame(body)
    display(product_by_name_or_description)

,categorie,date_creation,description,id,nom,prix,quantite_stock
0,Ordinateurs,2026-09-25T16:47:57.283631,"Tour gaming avec ventilation RGB, Core i7, RTX...",2,PC Fixe Gaming Tower RGB,1450.0,5

### Modifier un produit

Mise à jour d'un produit existant avec le token administrateur.

In [78]:
def modify_product(token,product):
    headers = {"Authorization": f"Bearer {token}"} if token else {}
    response = requests.put(
        f"http://localhost:5000/api/produits/{product['id']}",
        json=product,
        headers=headers,
    )
    return response.status_code, response.json()

In [79]:
product={ "id": 7,
          "nom": "modification ok",
          "categorie": "Autres",
          "description" : "à voir",
          "quantite_stock" : 100
}

status, body = modify_product(admin_token, product)

new_line = pd.DataFrame([body])
new_line

,categorie,date_creation,description,id,nom,prix,quantite_stock
0,Autres,2026-09-25T16:47:57.349812,à voir,7,modification ok,89.0,100

## 5. Gérer les commandes

Dernière étape du parcours : tester la consultation et la gestion des commandes.

### 5.1 Préparer le test d'une commande

On récupère un produit du catalogue ayant encore du stock afin de tester la création d'une commande avec une quantité.

In [80]:
ORDERS_URL = "http://localhost:5000/api/commandes"

status, catalogue = get_products(admin_token)
if status == 200 and catalogue:
    produits_disponibles = [
        produit for produit in catalogue
        if produit["quantite_stock"] > 0
    ]
    produit_commande = produits_disponibles[0]
    produit_id = produit_commande["id"]
    stock_initial = produit_commande["quantite_stock"]
    quantite_commandee = 1

    print("Produit sélectionné :", produit_commande["nom"])
    print("Stock avant commande :", stock_initial)
    print("Produit ID :", produit_id)
else:
    print("Impossible de récupérer un produit disponible :", status, catalogue)

Produit sélectionné : PC Portable Gamer 15.6" RTX 4060
Stock avant commande : 8
Produit ID : 1

### 5.2 Créer une commande

Le client fournit l'adresse de livraison, le produit et la quantité souhaitée. Le stock doit être diminué automatiquement.

In [81]:
client_headers = {"Authorization": f"Bearer {client_token}"}
admin_headers = {"Authorization": f"Bearer {admin_token}"}

commande_payload = {
    "adresse_livraison": "1 rue des Tests, Paris",
    "produits": [
        {
            "produit_id": produit_id,
            "quantite": quantite_commandee,
        }
    ],
}

response = requests.post(
    ORDERS_URL,
    json=commande_payload,
    headers=client_headers,
)

print("Status :", response.status_code)
print("Type de contenu :", response.headers.get("Content-Type"))

try:
    commande = response.json()
except ValueError:
    commande = {}
    print("Réponse non JSON :")
    print(response.text[:2000])

if response.status_code == 201 and commande:
    commande_resume = pd.DataFrame([{
        "id": commande.get("id"),
        "adresse_livraison": commande.get("adresse_livraison"),
        "statut": commande.get("statut"),
    }])
    display(commande_resume)

    commande_id = commande["id"]
    lignes_commande = pd.DataFrame(commande.get("lignes", []))
    display(lignes_commande)

    status, catalogue_apres_commande = get_products(admin_token)
    produit_apres_commande = next(
        produit for produit in catalogue_apres_commande
        if produit["id"] == produit_id
    )
    stock_resume = pd.DataFrame([{
        "produit": produit_apres_commande["nom"],
        "stock_avant": stock_initial,
        "quantite_commandee": quantite_commandee,
        "stock_apres": produit_apres_commande["quantite_stock"],
    }])
    display(stock_resume)
else:
    print("La commande n'a pas été créée.")
    if commande:
        display(pd.DataFrame([commande]))

Status : 201
Type de contenu : application/json

   id       adresse_livraison      statut
0   1  1 rue des Tests, Paris  en_attente

   id  order_id  prix_unitaire  product_id  quantity
0   1         1          999.0           1         1

,produit,stock_avant,quantite_commandee,stock_apres
0,"PC Portable Gamer 15.6"" RTX 4060",8,1,7

### 5.3 Consulter l'historique, le détail et les lignes

Un client peut consulter ses commandes, le détail d'une commande et son contenu.

In [82]:
if "commande_id" in globals():
    response = requests.get(ORDERS_URL, headers=client_headers)
    historique = response.json().get("orders", [])
    print("Historique client - status :", response.status_code)
    display(pd.DataFrame(historique))

    response = requests.get(
        f"{ORDERS_URL}/{commande_id}",
        headers=client_headers,
    )
    detail = response.json()
    print("Détail commande - status :", response.status_code)
    display(pd.DataFrame([detail]))

    response = requests.get(
        f"{ORDERS_URL}/{commande_id}/lignes",
        headers=client_headers,
    )
    lignes = response.json().get("lignes", [])
    print("Lignes commande - status :", response.status_code)
    display(pd.DataFrame(lignes))
else:
    print("Aucune commande disponible pour les consultations.")

Historique client - status : 200

,adresse_livraison,date_commande,id,lignes,statut,utilisateur_id
0,"1 rue des Tests, Paris",2026-09-25T16:47:57.562506,1,"[{'id': 1, 'order_id': 1, 'prix_unitaire': 999...",en_attente,2

Détail commande - status : 200

,adresse_livraison,date_commande,id,lignes,statut,utilisateur_id
0,"1 rue des Tests, Paris",2026-09-25T16:47:57.562506,1,"[{'id': 1, 'order_id': 1, 'prix_unitaire': 999...",en_attente,2

Lignes commande - status : 200

   id  order_id  prix_unitaire  product_id  quantity
0   1         1          999.0           1         1

### 5.4 Gestion administrateur

L'administrateur peut consulter toutes les commandes et modifier leur statut. Un client ne peut pas modifier le statut.

In [83]:
if "commande_id" in globals():
    response = requests.get(ORDERS_URL, headers=admin_headers)
    toutes_les_commandes = response.json().get("orders", [])
    print("Toutes les commandes - status :", response.status_code)
    display(pd.DataFrame(toutes_les_commandes))

    resultats_statut = []

    response = requests.patch(
        f"{ORDERS_URL}/{commande_id}",
        json={"statut": "validée"},
        headers=client_headers,
    )
    resultats_statut.append({
        "acteur": "client",
        "action": "Modifier le statut",
        "status_http": response.status_code,
        "statut_retourne": response.json().get("statut"),
        "message": response.json().get("error", "Accès refusé"),
    })

    response = requests.patch(
        f"{ORDERS_URL}/{commande_id}",
        json={"statut": "validée"},
        headers=admin_headers,
    )
    resultats_statut.append({
        "acteur": "administrateur",
        "action": "Modifier le statut",
        "status_http": response.status_code,
        "statut_retourne": response.json().get("statut"),
        "message": response.json().get("error", "Statut modifié"),
    })

    display(pd.DataFrame(resultats_statut))
else:
    print("Aucune commande disponible pour la gestion administrateur.")

Toutes les commandes - status : 200

,adresse_livraison,date_commande,id,lignes,statut,utilisateur_id
0,"1 rue des Tests, Paris",2026-09-25T16:47:57.562506,1,"[{'id': 1, 'order_id': 1, 'prix_unitaire': 999...",en_attente,2

,acteur,action,status_http,statut_retourne,message
0,client,Modifier le statut,403,NaN,Accès réservé aux administrateurs
1,administrateur,Modifier le statut,200,validee,Statut modifié